app:
  name: kdbe
  version: 1.0.0


## RDB Property (AWS RDS), MongoDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://toy-db.c0yxo9fizkk3.ap-northeast-2.rds.amazonaws.com:3306/kdproject

    username: admin
    password: rlatpdud13795
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  data:
    mongodb:
      host: 54.180.24.185
      port: 27017
      database: my-service

logging:
  level:
    com.example.kdbe: debug
