# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make Gradle wrapper script executable
      run: |
          chmod +x ./gradlew
     
    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Docker Buildx
      users: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.SECRET_ID }}
        password: ${{ secrets.SECRET_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t kimkagyun/kdbe:latest

    - name: Push Docker Image
      run: docker push -t kimkagyun/kdbe:latest

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SECRET_PEMKEY }}
        script: |
          docker pull kimkagyun/kdbe:latest
          docker stop kimkagyun
          docker rm kimkagyun
          docker run -d -p 80:8080 --name kdbe kimkagyun/kdbe:latest


