name: Java CI with Gradle and Docker Buildx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Make Gradle wrapper script executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        run: echo ${{ secrets.SECRET_PASSWORD }} | docker login -u ${{ secrets.SECRET_ID }} --password-stdin

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build and Push Docker Image with Buildx
        run: |
          docker buildx build -t kimkagyun/kdbe:latest .
          docker buildx build --push -t kimkagyun/kdbe:latest .

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SECRET_PEMKEY }}
          port: 22
          script: |
            sudo docker pull kimkagyun/kdbe:latest
            sudo docker stop kimkagyun
            sudo docker rm kimkagyun
            sudo docker run -d -p 80:8080 --name kdbe kimkagyun/kdbe:latest
